
namespace ConsoleApplication1
{
    [attributeusage(target_runtimeclass)]
    attribute ComServerAttribute
    {
        String Clsid;
        String Executable;
    }

    [attributeusage(target_runtimeclass)]
    attribute DisplayNameAttribute
    {
        String DisplayName;
    }

    [attributeusage(target_runtimeclass)]
    attribute LaunchAndActivationPermissionAttribute
    {
        String SDDL;
    }

    [ComServer("{C0A3D611-3E3D-4D0D-8D3D-3D3D3D3D3D3D}", "ConsoleApplication1.exe")]
    [DisplayName("My COM Server")]
    [LaunchAndActivationPermission("D:P(A;;GA;;;SY)(A;;GA;;;BA)")]
    runtimeclass MyCOMServer
    {
        MyCOMServer();
        void DoSomething();
    }

}